name: lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, sodium
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run phpstan
        run: composer lint
