name: phpunit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: phpunit-php-${{ matrix.php }}

    runs-on: ubuntu-latest

    timeout-minutes: 45

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, sodium
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run phpunit
        run: composer test
